SELECT MIN(WEIGHT) FROM ITEMS;

SELECT W.WNAME, C.CITY FROM WAREHOUSES W, CITY C WHERE W.CITY_ID = C.CITY_ID 
AND C.CITY  ='PUNE'

SELECT C.CNAME, O.ONO, O.ODATE, I.DESCRIPTION FROM ITEMS_ORDERS IO, CUSTOMER C,
ORDERS O, ITEMS I WHERE IO.ONO = O.ONO AND O.CNO = C.CNO AND CNAME = 'PATIL';


SELECT * FROM WAREHOUSES WHERE WID = (
  SELECT WID FROM STORES GROUP BY WID ORDER BY COUNT(*) DESC LIMIT 1
);


SELECT * FROM ITEMS WHERE ITEMNO = (
  SELECT ITEMNO FROM ITEMS_ORDERS GROUP BY ITEMNO ORDER BY COUNT(*) LIMIT 1
);


SELECT C.CNAME, I.DESCRIPTION, I.WEIGHT, I.COST, O.ODATE, C.CU_CITY FROM ORDERS O
INNER JOIN CUSTOMER C ON O.CNO = C.CNO
INNER JOIN ITEMS_ORDERS IO ON IO.ONO = O.ONO
INNER JOIN ITEMS I ON I.ITEMNO = IO.ITEMNO;